/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
// import { IntegrationItem as IntegrationItemType } from "./types";

interface IntegrationItemProps {
  item: {
    icon?: string;
    name: string;
  };
}

export function IntegrationItem({ item: { icon, name } }: IntegrationItemProps)  {
  return (
    <div className="flex gap-2 justify-center items-center px-3 py-2 whitespace-nowrap rounded-3xl border border-dashed border-neutral-900">
      <img
        loading="lazy"
        src={icon}
        alt={`${name} icon`}
        className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
      />
      <p className="self-stretch my-auto">{name}</p>
    </div>
  );
}
