/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";
import SignInButton from "./SignInButton";

const Header: React.FC = () => {
  return (
    <header className="free-area flex flex-wrap justify-start items-center h-[50px] w-[100%] max-md:max-w-full mt-5 border-red-600">
      <Logo />
      <Navigation />
      <SignInButton />
    </header>
  );
};

export default Header;
