/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TagList from "./TagList";
import EmailSignup from "./EmailSignup";
import Screen from "./Screen";
import Description from "./Description";
import Header from "./Header";
import MouseTracker from "./MouseTracker";

const HeroSection: React.FC = () => {
  return (
    <MouseTracker>
      <Header />
      <section className="mt-10 ">
        <h1 className="group text-[140px] tracking-tighter uppercase leading-[120px] text-neutral-900 max-xl:text-[100px] max-xl:leading-[85px] max-md:text-[60px] max-md:leading-[50px]">
          <span className="relative z-[4] inline-block  pr-5 group-hover:bg-[#AFEDFF] bg-clip-content transition-colors duration-300">
            IT-consultants, ship&nbsp;{" "}
          </span>
          <span className="inline-block pr-5 group-hover:bg-[#AFEDFF] transition-colors duration-300">
            production-ready{" "}
          </span>
          <span className="inline-block pr-5 group-hover:bg-[#AFEDFF] transition-colors duration-300">
            apps x10 faster&nbsp;
          </span>
        </h1>

        <div className="flex flex-wrap gap-3 items-center self-start mt-5  leading-none">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0d95f6465573d9ea8cbf5f565440eb2548c8db0b5d731eacdc20601820543cd5?placeholderIfAbsent=true&apiKey=91b63c92872e4a9fbc65bfa4b6faa19c"
            alt=""
            className="object-contain shrink-0 aspect-[0.61] w-[11px]"
          />
          <span>Hybrid low-code </span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e2a2f97a06f3f0f8b248d41757b82fb2efc5d0517df3d89c882dca360ad292d2?placeholderIfAbsent=true&apiKey=91b63c92872e4a9fbc65bfa4b6faa19c"
            alt=""
            className="object-contain shrink-0 aspect-[1.61] w-[29px]"
          />
          <span className="relative max-md:max-w-full after:content-[''] after:inline-block after:bg-neutral-900 after:w-3 after:h-[18px] after:shrink-0 after:ml-3">
            full-code platform with the resource-based pricing model
          </span>
        </div>

        <TagList />
        <EmailSignup />
        <div className="ml-auto pl-[50%] w-full max-md:pl-0">
          <Description paragraphText="Built by Clojure-developers for result-oriented developers" />
          <Screen title="Product tour" width="w-full">
            <img
              loading="lazy"
              src="/images/productTour.png"
              alt="Product tour"
              className="object-contain w-full h-auto border border-solid border-neutral-900 max-md:w-full max-md:h-auto"
            />
          </Screen>
        </div>
      </section>
    </MouseTracker>
  );
};

export default HeroSection;
