/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import HeroSection from "./HeroSection";

const MainComponent: React.FC = () => {
  return (
    <main className="flex flex-col px-5  border-red-600">
      <Header />
      <HeroSection />
    </main>
  );
};

export default MainComponent;
