/**
 * This code was generated by Builder.io.
 */
import React from "react";

const navigationItems = [
  { label: "PRICING", href: "#" },
  { label: "DOCS", href: "#" },
  { label: "RESOURCES", href: "#", hasDropdown: true },
  { label: "ROADMAP", href: "#" },
];

const Navigation: React.FC = () => {
  return (
    <nav className="box-border fixed right-1/2 transform translate-x-1/2 bg-white bg-opacity-0 h-[50px] max-sm:mt-18 max-sm:ml-2.5 max-sm:h-auto max-sm:w-full max-sm:top-[80px]">
      <ul className="flex gap-2 items-center p-1 my-auto text-base font-medium tracking-wide whitespace-nowrap rounded-3xl backdrop-blur-[10px] bg-white bg-opacity-20 min-w-[240px] text-neutral-900 max-md:max-w-full max-sm:w-full max-sm:flex-wrap max-sm:gap-1 max-sm:ml-2.5">
        {navigationItems.map((item, index) => (
          <li
            key={index}
            className="gap-2 self-stretch px-6 py-2 my-auto text-center rounded-3xl cursor-pointer min-h-[40px] max-md:px-5 flex-shrink-0"
          >
            {item.hasDropdown ? (
              <div className="flex gap-2 justify-center items-center self-stretch my-auto">
                <span>{item.label}</span>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/1cde407b4b996d4e859f9d2ddcd7e5c7e6d0ef153298a2b7f2608068ed67a56d?placeholderIfAbsent=true&apiKey=91b63c92872e4a9fbc65bfa4b6faa19c"
                  alt=""
                  className="object-contain shrink-0 aspect-[1.3] fill-neutral-900 w-[13px]"
                />
              </div>
            ) : (
              item.label
            )}
          </li>
        ))}
      </ul>
    </nav>
  );
};

export default Navigation;
