/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TextBlock from "./TextBlock";

const SliderHeader: React.FC = () => {
  const items = [
    { subtitle: "/ FAST", title: "Drag & Drop" },
    { subtitle: "/ NO LIMITS", title: "Custom code" },
  ];

  return (
    <section className="flex flex-wrap gap-5 justify-between self-stretch w-full text-neutral-900 max-md:max-w-full">
      {items.map((item, index) => (
        <TextBlock key={index} subtitle={item.subtitle} title={item.title} />
      ))}
    </section>
  );
};

export default SliderHeader;
