/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TextBlockProps {
  subtitle: string;
  title: string;
}

const TextBlock: React.FC<TextBlockProps> = ({ subtitle, title }) => {
  return (
    <div className="flex flex-col max-md:max-w-full">
      <h2 className="self-start text-2xl leading-none">{subtitle}</h2>
      <h1 className="text-7xl font-medium tracking-tighter leading-none max-md:max-w-full max-md:text-4xl">
        {title}
      </h1>
    </div>
  );
};

export default TextBlock;
