/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { AppSection, AppSectionProps } from "./AppSection";

const leftColumnApps: AppSectionProps[] = [
  {
    title: "LMS",
    isExpanded: false,
    features: ["Unlimited users", "Custom widgets for domain-specific tasks"],
    counter: "[.1.]",
  },
  {
    title: "CRM",
    isExpanded: true,
  },
  {
    title: "ERP",
    isExpanded: true,
  },
];

const rightColumnApps: AppSectionProps[] = [
  {
    title: "Interactive Dashboard",
    isExpanded: true,
  },
  {
    title: "Admin Panel",
    isExpanded: true,
  },
];

const CustomerApps = () => {
  return (
    <div className="self-stretch mt-10 w-full max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          {leftColumnApps.map((app, index) => (
            <AppSection key={index} {...app} />
          ))}
        </div>
        <div className="flex flex-col ml-[6%] w-6/12 max-md:ml-0 max-md:w-full">
          {rightColumnApps.map((app, index) => (
            <AppSection key={index} {...app} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default CustomerApps;
