/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface IDEButtonProps {
  icon?: string;
  name: string;
  iconAlt?: string;
}

export const IDEButton: React.FC<IDEButtonProps> = ({ icon, name, iconAlt = "" }) => {
  return (
    <li 
      className="flex gap-2 h-[48px] justify-center items-center px-3 py-2 pl-6 pr-6 text-base font-medium tracking-wide  whitespace-nowrap rounded-3xl border border-dashed border-neutral-900 "
      aria-label={name}
    >
      {icon && (
        <img 
          loading="lazy" 
          src={icon} 
          alt={iconAlt}
          className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square" 
        />
      )}
      <span className="self-stretch my-auto text-[24px]">{name}</span>
    </li>
  );
};