/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import { IDEButton } from "./IDEButton";

interface IDE {
  name: string;
  icon?: string;
  iconAlt?: string;
}

const ides: IDE[] = [
  { name: "Vim" },
  { name: "Sublime", icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/03a44ff080d9ce6bf90d0a8939f3ed3e691d7c8f495ae96a317c5a36b32bd0bc?placeholderIfAbsent=true&apiKey=91b63c92872e4a9fbc65bfa4b6faa19c", iconAlt: "Sublime Text editor icon" },
  { name: "others IDE" },
  { name: "JetBrains", icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/cc08c74b2b46dd9b5e610ef8be47a96c5c46411c10f37fb207618449524fa6ee?placeholderIfAbsent=true&apiKey=91b63c92872e4a9fbc65bfa4b6faa19c", iconAlt: "JetBrains IDE icon" },
  { name: "Visual Studio Code", icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/70e99cbf8695979956a4fe96d898e3144097560925e9aa8254e1ccc3ab88c87e?placeholderIfAbsent=true&apiKey=91b63c92872e4a9fbc65bfa4b6faa19c", iconAlt: "VS Code editor icon" },
  { name: "EMACS" },
  { name: "Vim" },
  { name: "Sublime" },
  { name: "others IDE" }
];

const IDESelector: React.FC = () => {
  return (
    
      <ul 
        className="flex gap-3 items-start mt-5 text-2xl leading-none text-neutral-900 w-[48%] max-md:w-full overflow-hidden"
        aria-label="IDE Selection"
      >
        {ides.map((ide, index) => (
          <IDEButton
            key={`${ide.name}-${index}`}
            name={ide.name}
            icon={ide.icon}
            iconAlt={ide.iconAlt}
          />
        ))}
      </ul>

  );
};

export default IDESelector;