/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export function Divider() {
  return (
    <div
      role="separator"
      aria-orientation="vertical"
      className="shrink-0 w-px border-r-2 border-dotted  border-gray-300 h-[216px] max-md:hidden"
    />
  );
}
