/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import { MetricCard, MetricCardProps } from "./MetricCard";
import { Divider } from "./Divider";
import metrics from "../../data/metrics.json";

export function MetricsSection() {
  return (
    <div
      aria-label="Key Metrics"
      className="flex flex-wrap gap-10 mt-40 max-md:mt-20"
    >
      {metrics.map((metric, index) => (
        <React.Fragment key={metric.id}>
          <MetricCard {...metric} />
          {index < metrics.length - 1 && <Divider />}
        </React.Fragment>
      ))}
    </div>
  );
}
