/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import { MetricCard, MetricCardProps } from "./MetricCard";
import { Divider } from "./Divider";
import metrics from "../../data/metrics.json";
import exp from "constants";

const MetricsSection=() =>{
  return (
    <div
      aria-label="Key Metrics"
      className="grid gap-5 grid-cols-1 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 mt-40  max-md:mt-20 max-md:mr-0"
    >
      {metrics.map((metric, index) => (
          <MetricCard key={metric.id} {...metric} />
      ))}
    </div>
  );
}

export default MetricsSection
