/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export interface MetricCardProps {
  id: string;
  number: string;
  unit?: string;
  prefix?: string;
  description: string;
  subtitle?: string;
}

export function MetricCard({
  number,
  unit,
  prefix,
  description,
  subtitle,
}: MetricCardProps) {
  return (
    <article className="flex flex-col self-start">
      <div className="flex items-end self-start font-medium font-robert-trial whitespace-nowrap">
        {prefix && (
          <span className="text-[40px] max-md:text-[28px]">{prefix}</span>
        )}
        <span className="text-[140px] tracking-tighter leading-[120px] max-md:text-[60px] max-md:leading-[50px]">
          {number}
        </span>
        {unit && <span className="text-[40px] max-md:text-[28px]">{unit}</span>}
      </div>
      <p className="mt-4 ">&gt; {description}</p>
      {subtitle && <p className="self-start mt-3  uppercase">/ {subtitle}</p>}
    </article>
  );
}
